version: "3.7"
services:
  app:
    build:
      args:
        user: dwihardik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: putra
    container_name: webputra
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - putra

  db:
    image: mysql:8.0
    container_name: dbputra
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: putra
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - putra

  nginx:
    image: nginx:alpine
    container_name: nginxputra
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginxputra:/etc/nginx/conf.d/
    networks:
      - putra

networks:
  putra:
    driver: bridge